version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindtech_app
    environment:
        DB_CONNECTION: mysql
    volumes:
      - ./:/var/www
      - ./docker/php-conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    networks:
      - mindtech
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: mindtech_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mindtech

  mysql:
    image: mysql:8.0
    container_name: mindtech_mysql
    ports:
      - "3306:3306"
    environment:
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      DB_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mindtech

volumes:
  db_data:

networks:
  mindtech:
